import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import SearchInput from "../components/SearchInput";
import Track from "../components/Track";
import Album from "../components/Album";

import { useAppContext } from "../context";
import axios from "axios";
import { useEffect, useState } from "react";
import { useRouter } from "next/router";

export default function AlbumPage() {
  const { query } = useRouter();

  const { globalState, setGlobalState } = useAppContext();
  const [album, setAlbum] = useState(query.id);
  const [url, setUrl] = useState(query.url);
  const [tracks, setTracks] = useState([]);
  const [artistInfo, setArtistInfo] = useState([]);

  useEffect(() => {
    const getAlbumData = async () => {
      const artist = globalState;
      try {
        const data = await axios.get(
          `/api/albums?id=${album}&artist=${artist}`
        );
        //setTracks(data.data.msg.topalbums.album);
      } catch (error) {}
    };
    getAlbumData();
  }, []);

  const handleChange = async (e) => {
    const artist = e.target.innerText;
    setGlobalState(artist);

    try {
      const data = await axios.get(`/api/albums?artist=${artist}`);
      setTracks(data.data.msg.topalbums.album);
    } catch (error) {}

    try {
      const data = await axios.get(`/api/artist?artist=${artist}`);
      //console.log(data);
      setArtistInfo(data.data.msg.artist);
    } catch (error) {}
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Link href="/">
        <a>Home page</a>
      </Link>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
